# Describe this package.

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

# exports_files(["diff_test.sh"])

exports_files(glob([
    "*.h",
    "*.cc",
    "*.sh",
]))
# exports_files(["check_macros.h"])
