[package]
name = "jaywalk-base"
version = "0.1.0"
authors = ["Alex Stark <alex@withheld.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
json5 = "0.4.1"
serde_default = "0.1.0"